return {
  'ThePrimeagen/harpoon',
  dependencies = { 'nvim-lua/plenary.nvim' },
  opts = {},
  keys = {
    {
      '<leader>hf',
      function()
        require('harpoon.mark').add_file()
      end,
      desc = 'Add file to harpoon',
    },
    {
      '<leader>hh',
      function()
        require('harpoon.ui').toggle_quick_menu()
      end,
      desc = 'Open Harpoon quick menu',
    },
    {
      '<leader>hj',
      function()
        require('harpoon.ui').nav_next()
      end,
      desc = 'Nav to next file in Harpoon',
    },
    {
      '<leader>hk',
      function()
        require('harpoon.ui').nav_prev()
      end,
      desc = 'Nav to previous file in Harpoon',
    },
    {
      '<leader>1',
      function()
        require('harpoon.ui').nav_file(1)
      end,
    },
    {
      '<leader>2',
      function()
        require('harpoon.ui').nav_file(1)
      end,
    },
    {
      '<leader>3',
      function()
        require('harpoon.ui').nav_file(3)
      end,
    },
    {
      '<leader>4',
      function()
        require('harpoon.ui').nav_file(4)
      end,
    },
    {
      '<leader>5',
      function()
        require('harpoon.ui').nav_file(5)
      end,
    },
    {
      '<leader>6',
      function()
        require('harpoon.ui').nav_file(6)
      end,
    },
    {
      '<leader>7',
      function()
        require('harpoon.ui').nav_file(7)
      end,
    },
    {
      '<leader>8',
      function()
        require('harpoon.ui').nav_file(8)
      end,
    },
    {
      '<leader>9',
      function()
        require('harpoon.ui').nav_file(9)
      end,
    },
    {
      '<leader>0',
      function()
        require('harpoon.ui').nav_file(10)
      end,
    },
  },
}
